server:
  port: 10004
  servlet:
    context-path: /yliu
spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1
    listener:
      simple:
        concurrency: 4
        max-concurrency: 10
  data:
    mongodb:
      uri: mongodb://admin:fasfmlmk23423@mongo_server:27017/crawler
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

yliu:
  auth: false
  cross: false

