server:
  port: 10004
  servlet:
    context-path: /yliu
spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1
  data:
    mongodb:
      uri: mongodb://mongo_server:27017/crawler

yliu:
  auth: false
  cross: false

